<a href="https://colab.research.google.com/github/dhruv20047228/Exploratory-Data-Analysis-Portfolio/blob/main/Exploratory_data_analysis_portfolio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sweetviz
!pip install -U ydata-profiling

Requirement already satisfied: sweetviz in /usr/local/lib/python3.11/dist-packages (2.3.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (2.0.2)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (1.15.2)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.11/dist-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.15.2)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.11.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.11/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: htmlmin==0.1.12 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.2)
Requirement already satisfied: imagehash==4.3.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: puremagic in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.28)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [ ]:
#Importing Libraries
#Core Libraries
import numpy as np
import pandas as pd
#Visualization Libraries
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats # Statistical Analytics
import seaborn as sns
#Auto EDA-reports
import sweetviz as sv
from ydata_profiling import ProfileReport

In [ ]:
df = pd.read_csv('/content/ert_bil_eur_d.tsv', sep='\t')

In [ ]:
df.info() ## datatypes,nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Columns: 12146 entries, statinfo,unit,currency\time to 1974M07D01
dtypes: float64(3400), object(8746)
memory usage: 4.0+ MB

In [ ]:
df.describe()

,2020M10D30,2020M10D29,2020M10D28,2020M10D27,2020M10D26,2020M10D22,2020M10D21,2020M10D20,2020M10D19,2020M10D16,...,2006M01D18,2006M01D17,2006M01D16,2006M01D13,2006M01D12,2006M01D11,2006M01D09,2006M01D06,2006M01D05,2006M01D04
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.00000,43.000000,43.000000,...,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000
mean,471.326806,476.038867,475.725074,477.051924,478.272812,479.126525,477.250347,478.05475,477.243915,476.482228,...,327.331853,324.980147,325.869286,321.288313,322.649383,324.954369,324.429911,328.412711,328.791962,330.713826
std,2605.751184,2635.834292,2633.187868,2641.661254,2648.812549,2654.196014,2641.472948,2646.16082,2642.264748,2637.744173,...,1757.779650,1744.349098,1750.524915,1721.230466,1731.267707,1745.211831,1742.786534,1765.301358,1768.649455,1779.529478
min,0.902080,0.904300,0.906620,0.907180,0.907550,0.902730,0.907540,0.91329,0.905880,0.909150,...,0.686400,0.685350,0.685450,0.681400,0.684600,0.688400,0.683400,0.688800,0.688800,0.688150
25%,4.305150,4.310900,4.299800,4.293150,4.288200,4.288300,4.294000,4.28600,4.277950,4.261550,...,2.399600,2.364650,2.374750,2.361750,2.365750,2.350950,2.353250,2.381850,2.367400,2.391550
50%,10.750000,10.770000,10.780000,10.820000,10.830000,10.840000,10.850000,10.82000,10.810000,10.800000,...,8.124000,8.106500,8.049000,8.047500,8.078000,8.031000,7.935000,7.929500,7.932500,7.933500
75%,89.353400,89.338100,89.291800,88.867250,88.921000,88.968800,89.392000,89.19055,88.851150,88.477250,...,57.530350,57.374900,57.403400,57.229350,57.339350,57.210550,57.346400,57.568400,57.573950,57.627950
max,17108.330000,17306.120000,17288.410000,17344.170000,17390.950000,17426.160000,17342.440000,17373.10000,17347.640000,17317.860000,...,11522.990000,11435.030000,11476.120000,11282.950000,11349.880000,11441.290000,11425.790000,11573.000000,11595.410000,11666.140000

In [ ]:
df.head(20)

,"statinfo,unit,currency\time",2021M07D30,2021M07D29,2021M07D28,2021M07D27,2021M07D26,2021M07D23,2021M07D22,2021M07D21,2021M07D20,...,1974M07D12,1974M07D11,1974M07D10,1974M07D09,1974M07D08,1974M07D05,1974M07D04,1974M07D03,1974M07D02,1974M07D01
0,"AVG,NAC,ALL",121.80000,121.76000,121.68000,121.85000,122.04000,122.19000,122.24000,122.39000,0.00000,...,:,:,:,:,:,:,:,:,:,:
1,"AVG,NAC,ARS",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
2,"AVG,NAC,AUD",1.6133,1.6062,1.6081,1.6029,1.6010,1.5944,1.5959,1.6089,1.6082,...,:,:,:,:,:,:,:,:,:,:
3,"AVG,NAC,BAM",:,1.95583,1.95583,1.95583,1.95583,1.95583,1.95583,1.95583,1.95583,...,:,:,:,:,:,:,:,:,:,:
4,"AVG,NAC,BGN",1.9558,1.9558,1.9558,1.9558,1.9558,1.9558,1.9558,1.9558,1.9558,...,:,:,:,:,:,:,:,:,:,:
5,"AVG,NAC,BRL",6.0716,6.0419,6.0931,6.1288,6.1546,6.1009,6.1029,6.1732,6.1633,...,:,:,:,:,:,:,:,:,:,:
6,"AVG,NAC,CAD",1.4791,1.4808,1.4840,1.4839,1.4804,1.4788,1.4779,1.4932,1.5023,...,:,:,:,:,:,:,:,:,:,:
7,"AVG,NAC,CHF",1.0771,1.0788,1.0802,1.0806,1.0826,1.0838,1.0829,1.0848,1.0838,...,3.6041,3.6066,3.6083,3.6006,3.5908,3.5922,3.5878,3.5907,3.6084,3.6170
8,"AVG,NAC,CNY",7.6838,7.6691,7.6722,7.6799,7.6426,7.6224,7.6153,7.6201,7.6305,...,:,:,:,:,:,:,:,:,:,:
9,"AVG,NAC,CZK",25.501,25.506,25.625,25.685,25.629,25.650,25.639,25.695,25.642,...,:,:,:,:,:,:,:,:,:,:
10,"AVG,NAC,DKK",7.4379,7.4376,7.4373,7.4371,7.4372,7.4382,7.4382,7.4385,7.4381,...,7.1871,7.2039,7.1871,7.1881,7.1727,7.1599,7.1972,7.1968,7.2255,7.2636
11,"AVG,NAC,DZD",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
12,"AVG,NAC,EGP",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
13,"AVG,NAC,GBP",0.85140,0.85080,0.85095,0.85503,0.85468,0.85543,0.85563,0.86363,0.86545,...,0.50573,0.50480,0.50442,0.50487,0.50618,0.50547,0.50545,0.50562,0.50472,0.50597
14,"AVG,NAC,HKD",9.2451,9.2272,9.1880,9.1915,9.1656,9.1420,9.1506,9.1518,9.1529,...,:,:,:,:,:,:,:,:,:,:
15,"AVG,NAC,HRK",7.50030,7.50850,7.50660,7.50640,7.52450,7.53530,7.53200,7.52760,7.52100,...,:,:,:,:,:,:,:,:,:,:
16,"AVG,NAC,HUF",357.20,358.08,359.72,359.43,361.65,359.13,357.87,360.20,359.45,...,:,:,:,:,:,:,:,:,:,:
17,"AVG,NAC,IDR",17184.46,17172.66,17117.84,17109.52,17084.23,17050.24,17063.23,17119.80,17143.51,...,:,:,:,:,:,:,:,:,:,:
18,"AVG,NAC,ILS",3.8403,3.8521,3.8492,3.8411,3.8487,3.8510,3.8524,3.8755,3.8810,...,:,:,:,:,:,:,:,:,:,:
19,"AVG,NAC,INR",88.3941,88.1675,87.8330,87.9130,87.7305,87.5905,87.6615,87.7895,87.9210,...,:,:,:,:,:,:,:,:,:,:

In [ ]:
df.shape ## will determine the shape of the dataset in the form of (rows,column)
df.columns ##column names

Index(['statinfo,unit,currency\time', '2021M07D30 ', '2021M07D29 ',
       '2021M07D28 ', '2021M07D27 ', '2021M07D26 ', '2021M07D23 ',
       '2021M07D22 ', '2021M07D21 ', '2021M07D20 ',
       ...
       '1974M07D12 ', '1974M07D11 ', '1974M07D10 ', '1974M07D09 ',
       '1974M07D08 ', '1974M07D05 ', '1974M07D04 ', '1974M07D03 ',
       '1974M07D02 ', '1974M07D01 '],
      dtype='object', length=12146)

In [ ]:
#Data Cleaning
df.isnull().sum() #Check if any data is missing or not
df=df.dropna()